import Head from "next/head";
import Particles from "react-particles-js";
import Hero from "../components/Home/Hero";
import HeroContent from "../components/Home/HeroContent";
import Header from "../components/navbar/Nav";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Wenoch | Project Work of Emmanuel Nwanochie.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fav.png"/>
      </Head>
      <Hero>
        <Header />
        <HeroContent />
      </Hero>
    </div>
  );
}
