import Head from "next/head";
import Particles from "react-particles-js";
import Hero from "../components/Home/Hero";
import HeroContent from "../components/Home/HeroContent";
import Header from "../components/navbar/Nav";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Wenoch | Project Work of Emmanuel Nwanochie.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <Header position="relative" zIndex={1} />
        <Particles
          zIndex={-1000000000000000000000000000000}
          width={"100%"}
          height={"95vh"}
          style={{ position: "absolute", top: 0, opacity: 0.5 }}
          params={{
            polygon: {
              enable: true,
              type: "inside",
              move: {
                radius: 10,
              },
            },
          }}
        />
        <HeroContent />
      </Hero>
    </div>
  );
}
